import Head from "next/head";
import Image from "next/image";
import styles from "../styles/chatrooms.module.css";
import Chatrooms from "./chatrooms";
import Link from "next/link";
import { Button } from "@mui/material";
import styled from "@emotion/styled";

export default function Home() {
  return (
    <div className={styles.chatroomsContainer}>
      <Head>
        <title>ChatLy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatSender>
        <Link href="/chatrooms">
          <Button
            style={{
              height: "150px",
              width: "250px",
              bottom: "100px",
            }}
          >
            Go to Chat!
          </Button>
        </Link>
      </ChatSender>
    </div>
  );
}

const ChatSender = styled.div`
  background-color: blue;
  border-style: outset;
  padding: 500px;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: white;
  border-radius: 5px;
  box-shadow: 0px 4px 14px -3px rgba(0, 0, 0, 0.7); /* offset-x, offset-y, blur-radius, spread-radius, color */
`;
